name: Build-Test-Deploy

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install
          cd ../frontend
          npm install || echo "No frontend dependencies"

      - name: Run backend tests
        run: |
          cd backend
          npm test

      - name: Build frontend
        run: |
          cd frontend
          echo "Frontend build step (if any)"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend

